# **************************************
# * Parameters for metprofile pipeline *
# **************************************

list_files: "/bulk/sycuro_bulk/lsycuro_labshare/kevin/kghs_metagenomics_2023/metaphlan4/utils/ref_list_merged_files_controls.txt"


# Path to sequences
path: "/bulk/sycuro_bulk/lsycuro_labshare/kevin/kghs_metagenomics_2023/metqc/output/bmtagger/"

#output_dir: "output"
output_dir: "output_with_controls"


# Metaphlan bowtie2 database.
metaphlan_database: "/bulk/IMCshared_bulk/shared/dbs/metaphlan4.0.5"

# Metaphlan database SGB ID to GTDB taxonomy file.
sgb_to_gtdb_tsv_file: "/bulk/IMCshared_bulk/shared/dbs/metaphlan4.0.5/mpa_vOct22_CHOCOPhlAnSGB_202212_SGB2GTDB.tsv"

# Nthreads metaphlan can use
threads: 8

# Are reads paired?
paired: TRUE

# If paired-end reads, suffix for forward reads
for: "_bmtagged_1.fastq"
# If paired-end reads, suffix for reverse reads
rev: "_bmtagged_2.fastq"

# If unpaired reads, suffix for reads
suff: "_bmt_merged_ELC_trimmed_filtered.fastq"
